blank_issues_enabled: false
version: 2.1
contact_links:
  - name: ðŸ’¬ Deep Agents Forum
    url: https://forum.langchain.com/c/oss-product-help-lc-and-lg/deep-agents/18
    about: General community discussions and support
  - name: ðŸ“š Deep Agents Documentation
    url: https://docs.langchain.com/oss/python/deepagents/overview
    about: View the official Deep Agents documentation
  - name: ðŸ“š API Reference Documentation
    url: https://reference.langchain.com/python/deepagents/
    about: View the official Deep Agents API reference documentation
  - name: ðŸ“š Documentation issue
    url: https://github.com/langchain-ai/docs/issues/new?template=05-deepagents.yml
    about: Report an issue related to the Deep Agents documentation
